[CI] git stash the local modify
	Save the local modify if possible and restore the modify if
	complete the push code

diff --git a/CI/pre-push b/CI/pre-push
--- a/CI/pre-push
+++ b/CI/pre-push
@@ -6,5 +6,25 @@ allownonascii="true"
 exec 1>&2
 
 
-make clean && make -j
-make -C examples/ clean && make -C examples
+echo "\x1b[1;36m Run CI ... \x1b[m"
+git stash               >/dev/null 2>&1
+
+# Build the source code
+make clean              >/dev/null 2>&1
+make -j                 >/dev/null 2>&1
+if [ $? != 0 ]; then
+    echo "\x1b[1;31m Build Code fail ... \x1b[m"
+    exit 1
+fi
+
+# Build the example soure code
+make -C examples/ clean >/dev/null 2>&1
+make -C examples        >/dev/null 2>&1
+if [ $? != 0 ]; then
+    echo "\x1b[1;31m Run the example code fail ... \x1b[m"
+    exit 1
+fi
+
+git stash pop           >/dev/null 2>&1
+echo "\x1b[1;36m Run CI Success ! \x1b[m"
+exit 0
